### ISSUE TITLE
Crashed trying to Play as Character

### ISSUE THREAD

**Issue by javaplus** [ManApart/quest-command#17]
```Create Barry
Created new Character Barry.
Barry wakes to An Open Field.
stat
You (Player) have 8/10 HP, 100/100 Focus and 100/100 Stamina. You are 50% encumbered (5/10 + 0% additional encumbrance).
Your stats:
        Perception: 1/1 (1/2xp)
        Strength: 1/1 (1/2xp)
        Wisdom: 1/1 (1/2xp)
        Climbing: 1/1 (1/4xp)
        Agility: 1/1 (1/4xp)
        Cooking: 1/1 (1/4xp)
        Smithing: 1/1 (1/4xp)
        Craftsmanship: 1/1 (1/4xp)
play as Barry
Exception in thread "main" java.lang.Exception: Response must have options.
        at core.commands.RequestResponseBuilder.build(RequestResponseBuilder.kt:16)
        at core.commands.RequestResponseBuilderKt.respond(RequestResponseBuilder.kt:96)
        at system.persistance.changePlayer.PlayAs.loadCharacter(PlayAs.kt:29)
        at system.persistance.changePlayer.PlayAs.execute(PlayAs.kt:14)
        at system.persistance.changePlayer.PlayAs.execute(PlayAs.kt:12)
        at core.events.EventListener.execute(EventListener.kt:8)
        at core.events.EventManager.executeEvent(EventManager.kt:93)
        at core.events.EventManager.executeEvents(EventManager.kt:58)
        at core.commands.CommandParser.splitAndParseCommand(CommandParser.kt:54)
        at core.commands.CommandParser.parseCommand(CommandParser.kt:32)
        at core.commands.CommandParsers.parseCommand(CommandParsers.kt:95)
        at core.commands.CommandParsers.parseCommand(CommandParsers.kt:91)
        at QuestCommandKt.main(QuestCommand.kt:14)

C:\Users\AdminG\Downloads>
```

**Comment by ManApart** [comment]
I believe that `Be Barry` should work successfully, but obviously this is a bug. I'll take a look.

**Comment by ManApart** [comment]
It's interpreting `play as barry` as `play asbarry` and looking for a character save with that name. The command should ignore the `as`...
